# frozen_string_literal: true

require 'rbconfig'

namespace :sdl2 do
  ext_dir = File.expand_path('ext/teek_sdl2', __dir__)
  lib_dir = File.expand_path('lib', __dir__)
  so_name = "teek_sdl2.#{RbConfig::CONFIG['DLEXT']}"

  desc "Compile teek-sdl2 C extension"
  task :compile do
    Dir.chdir(ext_dir) do
      sh RbConfig.ruby, 'extconf.rb' unless File.exist?('Makefile')
      sh 'make'
    end
    cp File.join(ext_dir, so_name), lib_dir
  end

  desc "Remove teek-sdl2 build artifacts"
  task :clobber do
    Dir.chdir(ext_dir) do
      sh 'make clean' if File.exist?('Makefile')
    end
    rm_f Dir.glob("#{ext_dir}/{Makefile,*.o,*.so,*.bundle,*.def,mkmf.log}")
    rm_f File.join(lib_dir, so_name)
  end
end
