# frozen_string_literal: true

require "minitest/autorun"
require "teek/mgba"
require "tempfile"

class TestMGBACore < Minitest::Test
  # Generated by: ruby teek-mgba/scripts/generate_test_rom.rb
  TEST_ROM = File.expand_path("fixtures/test.gba", __dir__)

  def setup
    skip "Run: ruby teek-mgba/scripts/generate_test_rom.rb" unless File.exist?(TEST_ROM)
    @core = Teek::MGBA::Core.new(TEST_ROM)
  end

  def teardown
    @core&.destroy unless @core.nil? || @core.destroyed?
  end

  # -- Dimensions --------------------------------------------------------------

  def test_width
    assert_equal 240, @core.width
  end

  def test_height
    assert_equal 160, @core.height
  end

  # -- Title -------------------------------------------------------------------

  def test_title
    assert_equal "TEEKTEST", @core.title
  end

  # -- Lifecycle ---------------------------------------------------------------

  def test_not_destroyed_initially
    refute @core.destroyed?
  end

  def test_destroy
    @core.destroy
    assert @core.destroyed?
  end

  def test_double_destroy_is_safe
    @core.destroy
    @core.destroy
    assert @core.destroyed?
  end

  def test_methods_raise_after_destroy
    @core.destroy
    assert_raises(RuntimeError) { @core.run_frame }
    assert_raises(RuntimeError) { @core.video_buffer }
    assert_raises(RuntimeError) { @core.video_buffer_argb }
    assert_raises(RuntimeError) { @core.audio_buffer }
    assert_raises(RuntimeError) { @core.set_keys(0) }
    assert_raises(RuntimeError) { @core.width }
    assert_raises(RuntimeError) { @core.height }
    assert_raises(RuntimeError) { @core.title }
  end

  # -- Frame emulation ---------------------------------------------------------

  def test_run_frame
    @core.run_frame
  end

  def test_video_buffer_size
    @core.run_frame
    buf = @core.video_buffer
    assert_kind_of String, buf
    assert_equal 240 * 160 * 4, buf.bytesize
  end

  def test_video_buffer_argb_size
    @core.run_frame
    buf = @core.video_buffer_argb
    assert_kind_of String, buf
    assert_equal 240 * 160 * 4, buf.bytesize
  end

  def test_video_buffer_argb_swaps_r_and_b
    @core.run_frame
    raw  = @core.video_buffer.unpack('V*')
    argb = @core.video_buffer_argb.unpack('V*')
    assert_equal raw.size, argb.size
    # Verify R↔B swap for first non-zero pixel
    idx = raw.index { |px| px != 0 } || 0
    px = raw[idx]
    expected = (px & 0xFF00FF00) |
               ((px & 0x000000FF) << 16) |
               ((px & 0x00FF0000) >> 16)
    assert_equal expected, argb[idx]
  end

  def test_audio_buffer_is_stereo_int16
    @core.run_frame
    buf = @core.audio_buffer
    assert_kind_of String, buf
    assert_equal 0, buf.bytesize % 4, "should be stereo int16 (4 bytes per frame)"
  end

  def test_multiple_frames
    10.times { @core.run_frame }
    assert_equal 240 * 160 * 4, @core.video_buffer.bytesize
  end

  # -- Input -------------------------------------------------------------------

  def test_set_keys
    @core.set_keys(Teek::MGBA::KEY_A | Teek::MGBA::KEY_START)
    @core.run_frame
    @core.set_keys(0)
    @core.run_frame
  end

  # -- Error handling ----------------------------------------------------------

  def test_nonexistent_file
    assert_raises(ArgumentError) { Teek::MGBA::Core.new("/no/such/game.gba") }
  end

  def test_invalid_extension
    Tempfile.create(["bad", ".txt"]) do |f|
      f.write("not a rom")
      f.flush
      assert_raises(ArgumentError) { Teek::MGBA::Core.new(f.path) }
    end
  end
end
